// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3FQ7UBsH-428fvpvO1Px7hmaULUw_6jY',
    appId: '1:211794612135:web:452e5668ec4a794a90b082',
    messagingSenderId: '211794612135',
    projectId: 'fir-auth-b01e0',
    authDomain: 'fir-auth-b01e0.firebaseapp.com',
    storageBucket: 'fir-auth-b01e0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtdg0z28TWYK87iOq54pQErjfQnAnWOhk',
    appId: '1:211794612135:android:ab78cc932c6a9b9390b082',
    messagingSenderId: '211794612135',
    projectId: 'fir-auth-b01e0',
    storageBucket: 'fir-auth-b01e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH3vF0iqNU5itEUM9SkBSL0VCW6jXVsJg',
    appId: '1:211794612135:ios:c92603e6712717de90b082',
    messagingSenderId: '211794612135',
    projectId: 'fir-auth-b01e0',
    storageBucket: 'fir-auth-b01e0.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH3vF0iqNU5itEUM9SkBSL0VCW6jXVsJg',
    appId: '1:211794612135:ios:c92603e6712717de90b082',
    messagingSenderId: '211794612135',
    projectId: 'fir-auth-b01e0',
    storageBucket: 'fir-auth-b01e0.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3FQ7UBsH-428fvpvO1Px7hmaULUw_6jY',
    appId: '1:211794612135:web:d034490f68dc8d5090b082',
    messagingSenderId: '211794612135',
    projectId: 'fir-auth-b01e0',
    authDomain: 'fir-auth-b01e0.firebaseapp.com',
    storageBucket: 'fir-auth-b01e0.appspot.com',
  );
}
